# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a0eb3a850be55a950055da2dfa22aad3ca666097f58914937b6565225de81bc86052c72413219a8ce4c163875c45540afcc2343b55fe3319f417c304b07e25

test:
  secret_key_base: 046e14faf5d8a631e529b9fcc5a3d9288f285f139e2e652481570515176824e727a788cecfc2b021af4b8fd3121e857a339bddea0dc986e82cd6a523b70c428d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
